language: d
sudo: false
script: dub build
before_install: 
- wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list --no-check-certificate -O /etc/apt/sources.list.d/d-apt.list
- apt-get update
- apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring 
- apt-get update
- apt-get install dub
- apt-get install dmd-bin
deploy: 
  provider: openshift
  app: drock
  domain: lenush
  user: galtiberiu@gmail.com
  password: GB219165
  skip_cleanup: true
